package zoopark.mybatis.model;

public class Animal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.BUILDING_ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    private Integer buildingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.ID
     *
     * @return the value of PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.ID
     *
     * @param id the value for PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @return the value of PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @param name the value for PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.BUILDING_ID
     *
     * @return the value of PUBLIC.ANIMAL.BUILDING_ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.BUILDING_ID
     *
     * @param buildingId the value for PUBLIC.ANIMAL.BUILDING_ID
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
}