package zoopark.mybatis.model;

public class Animal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.ID
     *
     * @return the value of PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.ID
     *
     * @param id the value for PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @return the value of PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @param name the value for PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Tue Mar 19 17:08:11 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}