package zoopark.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import zoopark.mybatis.model.AnimalZooKeeper;

@Mapper
public interface AnimalZooKeeperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL_ZOOKEEPER
     *
     * @mbg.generated Tue Mar 26 14:20:33 EET 2019
     */
    int insert(AnimalZooKeeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL_ZOOKEEPER
     *
     * @mbg.generated Tue Mar 26 14:20:33 EET 2019
     */
    List<AnimalZooKeeper> selectAll();
}