package zoopark.mybatis.dao;

import org.mybatis.cdi.Mapper;
import zoopark.mybatis.model.ZooKeeper;

import java.util.List;

@Mapper
public interface ZooKeeperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZOOKEEPER
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZOOKEEPER
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    int insert(ZooKeeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZOOKEEPER
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    ZooKeeper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZOOKEEPER
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    List<ZooKeeper> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ZOOKEEPER
     *
     * @mbg.generated Thu Mar 21 11:37:36 EET 2019
     */
    int updateByPrimaryKey(ZooKeeper record);
}